### ISSUE TITLE
productionize bot

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dewey#5]
At the moment testing will be very manual. 

But we'll need to:

- [x] Setup initial Capistrano tooling for deployment
- [x] Install Rubocop, create yml file
- [x] Install SimpleCov and Coveralls, create initial config
- [x] Create Rakefile with default rake tasks for running rubocop, rspec, coveralls/simplecov
- [x] Setup project in Circle-CI, set low threshold for now, since unsure how to test `Server` ~75%
- [x] Wire up Coveralls and CircleCI
- [x] [Add Gemnasium for deps monitoring]( #26 )
- [ ] [Identify + configure VM to deploy bot on.](https://github.com/ucsdlib/ops-requests/issues/6)
- [ ] [Setup all the Ansible things]( #24  )
- [ ] [Get the API token in the env-variables repo](https://github.com/ucsdlib/env-variables/issues/26)
- [ ] [Configure app to be managed via Deploybot]( #25 )
